"""Integration test — full pipeline end-to-end on test fixture videos.

Requires:
- GPU with Real-ESRGAN models
- Test fixtures generated by scripts/generate_test_fixtures.sh
- FFmpeg available
"""

import pytest
import os
from pathlib import Path
from unittest.mock import patch

from src.pipeline.upscaler import process_video
from src.pipeline.detector import VRLayout
from src.utils.ffmpeg import get_video_metadata, has_audio


FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _fixture_exists(name):
    return (FIXTURES_DIR / name).exists()


@pytest.mark.integration
class TestFullPipeline2D:
    """End-to-end 2D upscaling test."""

    @pytest.mark.skipif(
        not _fixture_exists("test_tiny.mp4"),
        reason="Test fixtures not generated — run scripts/generate_test_fixtures.sh",
    )
    def test_tiny_2d_upscale(self, tmp_path):
        """Upscale a 64x64 video to 256x256 — fastest possible integration test."""
        input_path = str(FIXTURES_DIR / "test_tiny.mp4")
        output_path = str(tmp_path / "output.mkv")

        result = process_video(
            input_path=input_path,
            output_path=output_path,
            model_name="RealESRGAN_x4plus",
            scale=4,
            tile_size=128,
            crf=23,
            layout=VRLayout.FLAT_2D,
            segment_size=50,
        )

        assert result["status"] == "success"
        assert os.path.exists(output_path)

        # Verify output metadata
        meta = get_video_metadata(output_path)
        assert meta["width"] == 256
        assert meta["height"] == 256

    @pytest.mark.skipif(
        not _fixture_exists("test_2d_720p.mp4"),
        reason="Test fixtures not generated",
    )
    def test_720p_upscale(self, tmp_path):
        """Upscale 720p → verify output resolution and audio."""
        input_path = str(FIXTURES_DIR / "test_2d_720p.mp4")
        output_path = str(tmp_path / "output.mkv")

        result = process_video(
            input_path=input_path,
            output_path=output_path,
            model_name="RealESRGAN_x4plus",
            scale=2,
            tile_size=256,
            crf=23,
            layout=VRLayout.FLAT_2D,
            segment_size=100,
        )

        assert result["status"] == "success"

        meta = get_video_metadata(output_path)
        assert meta["width"] == 2560  # 1280 * 2
        assert meta["height"] == 1440  # 720 * 2

        # Audio should be preserved
        assert has_audio(output_path)


@pytest.mark.integration
class TestFullPipelineVR:
    """End-to-end VR upscaling tests."""

    @pytest.mark.skipif(
        not _fixture_exists("test_SBS_vr.mp4"),
        reason="Test fixtures not generated",
    )
    def test_sbs_upscale(self, tmp_path):
        """SBS VR upscale — each eye should be upscaled independently."""
        input_path = str(FIXTURES_DIR / "test_SBS_vr.mp4")
        output_path = str(tmp_path / "output_sbs.mkv")

        result = process_video(
            input_path=input_path,
            output_path=output_path,
            model_name="RealESRGAN_x4plus",
            scale=2,
            tile_size=256,
            crf=23,
            layout=VRLayout.SBS,
            segment_size=100,
        )

        assert result["status"] == "success"
        assert result["layout"] == "sbs"

        meta = get_video_metadata(output_path)
        # Input: 1280x640, SBS → per-eye 640x640, scale 2x → 1280x1280 per eye → 2560x1280
        assert meta["width"] == 2560
        assert meta["height"] == 1280

    @pytest.mark.skipif(
        not _fixture_exists("test_OU_vr.mp4"),
        reason="Test fixtures not generated",
    )
    def test_ou_upscale(self, tmp_path):
        """OU VR upscale — top/bottom eyes upscaled independently."""
        input_path = str(FIXTURES_DIR / "test_OU_vr.mp4")
        output_path = str(tmp_path / "output_ou.mkv")

        result = process_video(
            input_path=input_path,
            output_path=output_path,
            model_name="RealESRGAN_x4plus",
            scale=2,
            tile_size=256,
            crf=23,
            layout=VRLayout.OU,
            segment_size=100,
        )

        assert result["status"] == "success"
        assert result["layout"] == "ou"

        meta = get_video_metadata(output_path)
        # Input: 640x1280, OU → per-eye 640x640, scale 2x → 1280x1280 → 1280x2560
        assert meta["width"] == 1280
        assert meta["height"] == 2560


@pytest.mark.integration
class TestTempCleanup:
    """Verify temp files are cleaned up after processing."""

    @pytest.mark.skipif(
        not _fixture_exists("test_tiny.mp4"),
        reason="Test fixtures not generated",
    )
    def test_temp_cleanup(self, tmp_path):
        """After processing, no temp segment directories should remain."""
        input_path = str(FIXTURES_DIR / "test_tiny.mp4")
        output_path = str(tmp_path / "output.mkv")

        temp_dir = tmp_path / "temp"
        temp_dir.mkdir(exist_ok=True)

        with patch("src.storage.volume.TEMP_DIR", temp_dir), \
             patch("src.config.TEMP_DIR", temp_dir):
            result = process_video(
                input_path=input_path,
                output_path=output_path,
                model_name="RealESRGAN_x4plus",
                scale=4,
                tile_size=128,
                crf=23,
                layout=VRLayout.FLAT_2D,
                segment_size=50,
            )

        # Temp directory should be empty (job cleaned up)
        remaining = list(temp_dir.iterdir())
        assert len(remaining) == 0, f"Orphaned temp files: {remaining}"
