"""Pydantic models for PPP Processor v2.0.

Converted from existing dataclasses in scripts/ with extended fields
for QA validation, worker management, and cost tracking.
"""

from __future__ import annotations

import enum
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------
class ContentType(str, enum.Enum):
    """Video content type classification."""
    VR_SBS = "vr_sbs"
    VR_TB = "vr_tb"
    VR_MONO = "vr_mono"
    FLAT_2D = "flat_2d"


class JobStatus(str, enum.Enum):
    """Extended job status including QA workflow stages."""
    PENDING = "pending"
    SCANNING = "scanning"
    SAMPLING = "sampling"
    SAMPLE_READY = "sample_ready"
    APPROVED = "approved"
    REJECTED = "rejected"
    PROCESSING = "processing"
    ENCODING = "encoding"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


# ---------------------------------------------------------------------------
# Video / VR metadata
# ---------------------------------------------------------------------------
class VideoInfo(BaseModel):
    """Video file metadata — refactored from upscale.py:VideoInfo dataclass."""
    width: int
    height: int
    fps: float
    duration: float
    codec: str
    bitrate: int
    is_vr: bool = False
    vr_type: Optional[str] = None  # "sbs", "tb", or None
    content_type: ContentType = ContentType.FLAT_2D
    file_path: Optional[str] = None
    file_size: Optional[int] = None
    file_hash: Optional[str] = None


class VRMetadata(BaseModel):
    """VR metadata — refactored from vr_metadata.py:VRMetadata dataclass."""
    is_vr: bool = False
    projection: str = "equirectangular"
    stereo_mode: str = "sbs"
    fov_horizontal: int = 180
    fov_vertical: int = 180
    source_filename: str = ""

    def to_filename_suffix(self) -> str:
        if not self.is_vr:
            return ""
        parts = []
        parts.append("360" if self.fov_horizontal == 360 else "180")
        if self.stereo_mode == "sbs":
            parts.append("sbs")
        elif self.stereo_mode == "tb":
            parts.append("tb")
        else:
            parts.append("mono")
        return "_" + "_".join(parts)


# ---------------------------------------------------------------------------
# Job models
# ---------------------------------------------------------------------------
class JobCreate(BaseModel):
    """Request model for creating a new processing job."""
    source_path: str
    output_path: Optional[str] = None
    model: Optional[str] = None
    scale: Optional[int] = None
    force_vr: Optional[bool] = None
    tier: str = "tier3"
    priority: int = 0
    scene_id: Optional[str] = None
    title: Optional[str] = None
    matte: bool = False  # Enable background removal / chroma key
    upscale: bool = False  # Enable upscale-only job (no QA sampling)


class JobResponse(BaseModel):
    """Response model for a job."""
    id: str
    scene_id: Optional[str] = None
    title: Optional[str] = None
    source_path: str
    output_path: Optional[str] = None
    tier: str = "tier3"
    model: Optional[str] = None
    scale: Optional[int] = None
    is_vr: bool = False
    matte: bool = False
    upscale: bool = False
    status: JobStatus = JobStatus.PENDING
    priority: int = 0
    created_at: Optional[datetime] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    error_message: Optional[str] = None
    processing_time_sec: Optional[float] = None
    progress: Optional[float] = None
    current_stage: Optional[str] = None
    worker_id: Optional[str] = None
    estimated_cost: Optional[float] = None
    actual_cost: Optional[float] = None


# ---------------------------------------------------------------------------
# QA models
# ---------------------------------------------------------------------------
class QASample(BaseModel):
    """QA validation sample for a job."""
    id: Optional[str] = None
    job_id: str
    sample_path: Optional[str] = None
    original_sample_path: Optional[str] = None
    ssim: Optional[float] = None
    psnr: Optional[float] = None
    sharpness: Optional[float] = None
    auto_approved: Optional[bool] = None
    human_approved: Optional[bool] = None
    reviewer_notes: Optional[str] = None
    created_at: Optional[datetime] = None
    reviewed_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# Processing plan
# ---------------------------------------------------------------------------
class ProcessingPlan(BaseModel):
    """Plan generated by the Router for how to process a video."""
    model: str
    scale: int
    worker_type: str  # "local" or "cloud"
    bitrate: str
    encoder: str = "libx265"
    content_type: ContentType = ContentType.FLAT_2D
    estimated_time_hours: Optional[float] = None
    estimated_cost: Optional[float] = None
    skip_ai: bool = False  # True for lanczos-only upscales
    tile_size: int = 512
    gpu_id: int = 0


# ---------------------------------------------------------------------------
# Worker status
# ---------------------------------------------------------------------------
class WorkerStatus(BaseModel):
    """Status of a processing worker."""
    id: str
    worker_type: str  # "local_gpu" or "cloud"
    status: str = "idle"  # idle, busy, offline, error
    current_job_id: Optional[str] = None
    gpu_name: Optional[str] = None
    gpu_utilization: Optional[float] = None
    memory_utilization: Optional[float] = None
    jobs_completed: int = 0
    total_processing_hours: float = 0.0
    total_cost: float = 0.0
    last_heartbeat: Optional[datetime] = None
    pod_id: Optional[str] = None
    extra: Dict[str, Any] = Field(default_factory=dict)
